#if !canImport(ObjectiveC)
import XCTest

extension RedisKitTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RedisKitTests = [
        ("testIsClosed", testIsClosed),
        ("testVersion", testVersion),
        ("testStruct", testStruct)
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(RedisKitTests.__allTests__RedisKitTests),
    ]
}
#endif
