#if !canImport(ObjectiveC)
import XCTest

extension RedisKitTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RedisKitTests = [
        ("testIsClosed", testIsClosed),
        ("testVersion", testVersion),
        ("testStruct", testStruct)
    ]
}

extension RedisSetTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RedisSetTests = [
        ("testCount", testCount),
        ("testInit", testInit),
        ("testInsert", testInsert),
        ("testMove", testMove),
        ("testPopRandomElement", testPopRandomElement),
        ("testPopRandomElements", testPopRandomElements),
        ("testRandomElement", testRandomElement),
        ("testRandomElements", testRandomElements),
        ("testRemoveAll", testRemoveAll),
        ("testRemove", testRemove),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(RedisKitTests.__allTests__RedisKitTests),
        testCase(RedisSetTests.__allTests__RedisSetTests),
    ]
}
#endif
