#if !canImport(ObjectiveC)
import XCTest

extension RedisKitTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RedisKitTests = [
        ("testCRUD", testCRUD),
        ("testExpire", testExpire),
        ("testHashCommands", testHashCommands),
        ("testIsClosed", testIsClosed),
        ("testListCommands", testListCommands),
        ("testPubSubMultiChannel", testPubSubMultiChannel),
        ("testPubSubSingleChannel", testPubSubSingleChannel),
        ("testSelect", testSelect),
        ("testSelectViaConfig", testSelectViaConfig),
        ("testSetCommands", testSetCommands),
        ("testSortedSetCommands", testSortedSetCommands),
        ("testStringCommands", testStringCommands),
        ("testStruct", testStruct),
        ("testVersion", testVersion),
    ]
}

extension RedisSetTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RedisSetTests = [
        ("testCount", testCount),
        ("testInit", testInit),
        ("testInsert", testInsert),
        ("testMove", testMove),
        ("testPopRandomElement", testPopRandomElement),
        ("testPopRandomElements", testPopRandomElements),
        ("testRandomElement", testRandomElement),
        ("testRandomElements", testRandomElements),
        ("testRemoveAll", testRemoveAll),
        ("testRemove", testRemove),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(RedisKitTests.__allTests__RedisKitTests),
        testCase(RedisSetTests.__allTests__RedisSetTests),
    ]
}
#endif
